-- 1. Rôle des outils (USERADMIN gère les rôles)
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
  COMMENT = 'Rôle des outils : chargement RAW et transformations';

-- SYSADMIN hérite de TRANSFORMER : l'administrateur garde la main
-- sur tout ce que le rôle créera
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;


-- 2. Objets (SYSADMIN gère les objets)
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Calcul du pipeline NYC Taxi';

CREATE DATABASE IF NOT EXISTS NYC_TAXI;

CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;


-- 3. Droits du rôle des outils (SYSADMIN, propriétaire des objets)
USE ROLE SYSADMIN;

-- Calcul : exécuter des requêtes
GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORMER;

-- Étage 1 : entrer dans la base
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;

-- Étage 2 : RAW, entrer + créer tables, stage et formats de fichier
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;

-- Étage 2 : les trois autres couches, entrer + créer tables et vues
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.STAGING TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
  ON SCHEMA NYC_TAXI.MARTS TO ROLE TRANSFORMER;


-- 4. Utilisateur de service (USERADMIN gère les utilisateurs)
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS AIRFLOW_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = NYC_TAXI_WH
  DEFAULT_NAMESPACE = NYC_TAXI.RAW
  COMMENT = 'Compte de service du script de chargement et d''Airflow';

-- DEFAULT_ROLE ne donne pas le rôle : il faut ce GRANT
GRANT ROLE TRANSFORMER TO USER AIRFLOW_SVC;

-- Clé publique : à attacher à part, hors Git (voir README)
-- ALTER USER AIRFLOW_SVC SET RSA_PUBLIC_KEY = '<clé publique sur une ligne>';